labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: invalid
    color: e4e669
    description: Something isn't right
  - name: question
    color: d876e3
    description: Further information is requested
  - name: wontfix
    color: fffffff
    description: This will not be worked on
  - name: priority: high
    color: ff0000
    description: High priority issue
  - name: priority: medium
    color: ff8000
    description: Medium priority issue
  - name: priority: low
    color: 00ff00
    description: Low priority issue
  - name: status: in progress
    color: 1d76db
    description: Work in progress
  - name: status: blocked
    color: ff0000
    description: Blocked by other issue
  - name: status: review needed
    color: ffb800
    description: Needs review
  - name: type: feature
    color: 0e8a16
    description: New feature
  - name: type: bugfix
    color: d73a4a
    description: Bug fix
  - name: type: refactor
    color: 6f42c1
    description: Code refactoring
  - name: type: performance
    color: 1d76db
    description: Performance improvement
